apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: front-end
        image: eu.gcr.io/gridwalls2/front_end:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80